"""
= Page Layout Compilation

This module handles loading and compiling physical Chameleon `.pt` templates
from disk, with standard fallback to an integrated HTML5 layout.
"""

from pathlib import Path
from chameleon import PageTemplate
from golem.config import GolemConfig

DEFAULT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>${title}</title>
    <style>
        :root {
            --golem-bg: #0f0f11;
            --golem-fg: #e2e8f0;
            --golem-primary: #818cf8;
            --golem-accent: #a5b4fc;
        }
        body {
            background-color: var(--golem-bg);
            color: var(--golem-fg);
            font-family: system-ui, sans-serif;
            margin: 0;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        #golem-header {
            background: #151518;
            padding: 15px 20px;
            border-bottom: 1px solid #222228;
        }
        #golem-header h1 {
            margin: 0;
            font-size: 1.5rem;
            color: var(--golem-primary);
        }
        #golem-wrapper {
            display: flex;
            flex: 1;
        }
        #golem-sidebar-left {
            width: 250px;
            background: #151518;
            padding: 20px;
            border-right: 1px solid #222228;
        }
        #golem-sidebar-left h3 {
            margin-top: 0;
            color: #94a3b8;
            font-size: 0.875rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }
        #golem-sidebar-left ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }
        #golem-sidebar-left li {
            margin-bottom: 10px;
        }
        #golem-sidebar-left a {
            color: var(--golem-fg);
            text-decoration: none;
            font-size: 1rem;
            transition: color 0.2s ease, padding-left 0.2s ease;
        }
        #golem-sidebar-left a:hover {
            color: var(--golem-accent);
            padding-left: 4px;
        }
        #golem-content {
            flex: 1;
            padding: 40px;
            max-width: 800px;
            line-height: 1.6;
        }
        #golem-sidebar-right {
            width: 200px;
            padding: 20px;
            border-left: 1px solid #222228;
        }
        #golem-footer {
            background: #151518;
            padding: 15px 20px;
            border-top: 1px solid #222228;
            text-align: center;
            font-size: 0.875rem;
            color: #64748b;
        }
    </style>
</head>
<body>
    <header id="golem-header">
        <h1>Golem Documentation</h1>
    </header>
    <div id="golem-wrapper">
        <aside id="golem-sidebar-left">
            <h3>Navigation</h3>
            <ul>
                <li><a href="index.html">Welcome</a></li>
                <li><a href="user_manual.html">User Manual</a></li>
                <li><a href="developer_guide.html">Developer Guide</a></li>
            </ul>
        </aside>
        <main id="golem-content">
            <h1>${title}</h1>
            <div tal:content="structure body_content" />
        </main>
        <aside id="golem-sidebar-right" class="golem-toc">
            <h4>On This Page</h4>
            <div tal:content="structure toc_html" />
        </aside>
    </div>
    <footer id="golem-footer">
        <p>Generated by Golem</p>
    </footer>
</body>
</html>
"""


class PageCompiler:
    """
    = PageCompiler

    Compiles body fragments into complete HTML pages using Chameleon templates.

    === Examples

    [source,python]
    ----
    >>> from golem.config import GolemConfig
    >>> from golem.templates import PageCompiler
    >>> config = GolemConfig(output_dir="dist")
    >>> compiler = PageCompiler(config)
    >>> html = compiler.compile_page("Sample Page", "<p>Paragraph content</p>", "")
    >>> "<title>Sample Page</title>" in html
    True
    >>> "<p>Paragraph content</p>" in html
    True

    ----
    """

    def __init__(self, config: GolemConfig):
        """
        == __init__

        Initialize the compiler with a Golem configuration.
        """
        self.config = config
        self.default_template = PageTemplate(DEFAULT_TEMPLATE)

    def compile_page(
        self,
        title: str,
        body_content: str,
        toc_html: str,
        template_path: Path | None = None,
    ) -> str:
        """
        == compile_page

        Compile a full static page.

        === Arguments

        - `title`:: Document title.
        - `body_content`:: Processed HTML body text.
        - `toc_html`:: Rendered Table of Contents HTML.
        - `template_path`:: Optional layout override path.
        """
        if template_path and template_path.exists():
            try:
                with open(template_path, "r", encoding="utf-8") as f:
                    template_content = f.read()
                template = PageTemplate(template_content)
            except Exception:
                template = self.default_template
        else:
            # Check for user's scaffolded custom templates directory first
            user_pt = Path(self.config.templates_dir) / "page.pt" if hasattr(self.config, "templates_dir") else None
            if user_pt and user_pt.exists():
                try:
                    with open(user_pt, "r", encoding="utf-8") as f:
                        template_content = f.read()
                    template = PageTemplate(template_content)
                except Exception:
                    template = self.default_template
            else:
                # Fallback to configured themes folder override if exists
                theme_dir = Path("themes") / self.config.theme
                skeleton_pt = theme_dir / "skeleton.pt"
                if skeleton_pt.exists():
                    try:
                        with open(skeleton_pt, "r", encoding="utf-8") as f:
                            template_content = f.read()
                        template = PageTemplate(template_content)
                    except Exception:
                        template = self.default_template
                else:
                    template = self.default_template

        return template(
            title=title,
            body_content=body_content,
            body=body_content,
            toc_html=toc_html,
            site_title=getattr(self.config, "site_title", "Golem Docs"),
            site_author=getattr(self.config, "site_author", "Anonymous"),
        )
