from golem.plugins import get_plugin_manager

def test_plugin_hook_trigger():
    pm = get_plugin_manager()
    # Define a mock plugin
    class MockPlugin:
        @get_plugin_manager().hookimpl
        def on_pre_parse(self, raw_content: str) -> str:
            return raw_content.replace("draft", "final")
            
    pm.register(MockPlugin())
    res = pm.hook.on_pre_parse(raw_content="This is a draft version.")
    # Pluggy returns results in a list
    assert "This is a final version." in res

def test_local_plugin_discovery(tmp_path):
    # Create a dynamic plugin file in the temporary directory
    plugin_content = """
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return f"Dynamic: {raw_content}"
"""
    plugin_file = tmp_path / "my_test_plugin.py"
    plugin_file.write_text(plugin_content, encoding="utf-8")
    
    # Load plugin manager passing the temporary path
    pm = get_plugin_manager(plugins_dir=tmp_path)
    
    # Verify hook can be triggered and the dynamic plugin worked
    res = pm.hook.on_pre_parse(raw_content="hello")
    assert "Dynamic: hello" in res

def test_local_plugin_error_isolation(tmp_path):
    # Create a broken plugin file (has runtime syntax/execution error)
    plugin_content = """
raise ValueError("Plugin failed intentionally during import!")
"""
    plugin_file = tmp_path / "broken_plugin.py"
    plugin_file.write_text(plugin_content, encoding="utf-8")
    
    # Loading plugins should not raise an exception, just skip broken ones
    pm = get_plugin_manager(plugins_dir=tmp_path)
    assert pm is not None


def test_plugin_hook_execution_in_build_pipeline(tmp_path):
    from golem.config import GolemConfig
    from golem.engine import BuildEngine
    
    # Scaffold temporary site
    content = tmp_path / "content"
    content.mkdir()
    (content / "index.adoc").write_text("This is draft content.\n", encoding="utf-8")
    
    # Create plugins folder and write a local hook plugin
    plugins_dir = tmp_path / "plugins"
    plugins_dir.mkdir()
    plugin_code = """
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return raw_content.replace("draft", "final")

@hookimpl
def on_post_render(html_content: str) -> str:
    return html_content.replace("Generated by Golem", "Generated by Golem and Plugin")
"""
    (plugins_dir / "test_hook.py").write_text(plugin_code, encoding="utf-8")
    
    # Configure Golem to load from this plugins directory
    config = GolemConfig(content_dir=str(content), output_dir=str(tmp_path / "dist"))
    setattr(config, "plugins_dir", str(plugins_dir))
    
    engine = BuildEngine(config)
    engine.build_site()
    
    # Verify that the pre_parse and post_render hooks were applied to the compiled output!
    out_html = (tmp_path / "dist" / "index.html").read_text(encoding="utf-8")
    assert "final content." in out_html
    assert "Generated by Golem and Plugin" in out_html


