from golem.plugins import get_plugin_manager


def test_plugin_hook_trigger():
    pm = get_plugin_manager()

    # Define a mock plugin
    class MockPlugin:
        @get_plugin_manager().hookimpl
        def on_pre_parse(self, raw_content: str) -> str:
            return raw_content.replace("draft", "final")

    pm.register(MockPlugin())
    res = pm.hook.on_pre_parse(raw_content="This is a draft version.")
    # Pluggy returns results in a list
    assert "This is a final version." in res


def test_local_plugin_discovery(tmp_path):
    # Create a dynamic plugin file in the temporary directory
    plugin_content = """
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return f"Dynamic: {raw_content}"
"""
    plugin_file = tmp_path / "my_test_plugin.py"
    plugin_file.write_text(plugin_content, encoding="utf-8")

    # Load plugin manager passing the temporary path
    pm = get_plugin_manager(plugins_dir=tmp_path)

    # Verify hook can be triggered and the dynamic plugin worked
    res = pm.hook.on_pre_parse(raw_content="hello")
    assert "Dynamic: hello" in res


def test_local_plugin_error_isolation(tmp_path):
    # Create a broken plugin file (has runtime syntax/execution error)
    plugin_content = """
raise ValueError("Plugin failed intentionally during import!")
"""
    plugin_file = tmp_path / "broken_plugin.py"
    plugin_file.write_text(plugin_content, encoding="utf-8")

    # Loading plugins should not raise an exception, just skip broken ones
    pm = get_plugin_manager(plugins_dir=tmp_path)
    assert pm is not None


def test_plugin_hook_execution_in_build_pipeline(tmp_path):
    from golem.config import GolemConfig
    from golem.engine import BuildEngine

    # Scaffold temporary site
    content = tmp_path / "content"
    content.mkdir()
    (content / "index.adoc").write_text("This is draft content.\n", encoding="utf-8")

    # Create plugins folder and write a local hook plugin
    plugins_dir = tmp_path / "plugins"
    plugins_dir.mkdir()
    plugin_code = """
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return raw_content.replace("draft", "final")

@hookimpl
def on_post_render(html_content: str) -> str:
    return html_content.replace("Generated by Golem", "Generated by Golem and Plugin")
"""
    (plugins_dir / "test_hook.py").write_text(plugin_code, encoding="utf-8")

    # Configure Golem to load from this plugins directory
    config = GolemConfig(content_dir=str(content), output_dir=str(tmp_path / "dist"))
    setattr(config, "plugins_dir", str(plugins_dir))

    engine = BuildEngine(config)
    engine.build_site()

    # Verify that the pre_parse and post_render hooks were applied to the compiled output!
    out_html = (tmp_path / "dist" / "index.html").read_text(encoding="utf-8")
    assert "final content." in out_html
    assert "Generated by Golem and Plugin" in out_html


def test_golem_add_subcommands_hookspec_execution():
    import click
    from click.testing import CliRunner
    from golem.plugins import get_plugin_manager, hookimpl

    pm = get_plugin_manager()

    class CustomCommandPlugin:
        @hookimpl
        def golem_add_subcommands(self, cli: click.Group) -> None:
            @cli.command("greet")
            @click.option("--name", default="World")
            def greet(name: str) -> None:
                click.echo(f"Hello, {name}!")

    pm.register(CustomCommandPlugin())

    @click.group()
    def test_cli():
        pass

    pm.hook.golem_add_subcommands(cli=test_cli)

    runner = CliRunner()
    result = runner.invoke(test_cli, ["greet", "--name", "Golem"])
    assert result.exit_code == 0
    assert "Hello, Golem!" in result.output


def test_config_plugins_package_loading(tmp_path, monkeypatch):
    from golem.config import GolemConfig
    from golem.plugins import get_plugin_manager

    # Create a dummy module package on sys.path
    pkg_dir = tmp_path / "custom_plugins"
    pkg_dir.mkdir()
    (pkg_dir / "__init__.py").write_text("", encoding="utf-8")
    (pkg_dir / "sample_plugin.py").write_text(
        """\
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return raw_content.upper()
""",
        encoding="utf-8",
    )
    monkeypatch.syspath_prepend(str(tmp_path))

    config = GolemConfig(plugins=["custom_plugins.sample_plugin"])
    pm = get_plugin_manager(config=config)

    res = pm.hook.on_pre_parse(raw_content="hello world")
    assert "HELLO WORLD" in res


def test_config_plugins_nonexistent_handled_gracefully():
    from golem.config import GolemConfig
    from golem.plugins import get_plugin_manager

    config = GolemConfig(plugins=["nonexistent.plugin.module.xyz"])
    pm = get_plugin_manager(config=config)
    assert pm is not None


def test_dynamic_subcommand_attached_to_click_main():
    from pathlib import Path
    from click.testing import CliRunner
    from golem.cli import main

    runner = CliRunner()
    with runner.isolated_filesystem():
        plugins_dir = Path("plugins")
        plugins_dir.mkdir()
        plugin_file = plugins_dir / "custom_cli_plugin.py"
        plugin_file.write_text(
            """\
import click
from golem.plugins import hookimpl

@hookimpl
def golem_add_subcommands(cli: click.Group) -> None:
    @cli.command("plugin-status")
    def plugin_status():
        click.echo("Plugin CLI is active!")
""",
            encoding="utf-8",
        )

        help_result = runner.invoke(main, ["--help"])
        assert help_result.exit_code == 0
        assert "plugin-status" in help_result.output

        cmd_result = runner.invoke(main, ["plugin-status"])
        assert cmd_result.exit_code == 0
        assert "Plugin CLI is active!" in cmd_result.output


def test_dynamic_subcommand_from_config_plugins(tmp_path, monkeypatch):
    from click.testing import CliRunner
    from golem.cli import main

    pkg_dir = tmp_path / "custom_cli_pkg"
    pkg_dir.mkdir()
    (pkg_dir / "__init__.py").write_text("", encoding="utf-8")
    (pkg_dir / "plugin.py").write_text(
        """\
import click
from golem.plugins import hookimpl

@hookimpl
def golem_add_subcommands(cli: click.Group) -> None:
    @cli.command("package-cmd")
    def package_cmd():
        click.echo("Executed package subcommand!")
""",
        encoding="utf-8",
    )
    monkeypatch.syspath_prepend(str(tmp_path))

    runner = CliRunner()
    with runner.isolated_filesystem():
        from pathlib import Path

        Path("golem.toml").write_text(
            """\
[site]
title = "Test Site"
author = "Test Author"

[plugins]
plugins = ["custom_cli_pkg.plugin"]
""",
            encoding="utf-8",
        )

        help_result = runner.invoke(main, ["--help"])
        assert help_result.exit_code == 0
        assert "package-cmd" in help_result.output

        cmd_result = runner.invoke(main, ["package-cmd"])
        assert cmd_result.exit_code == 0
        assert "Executed package subcommand!" in cmd_result.output
