from golem.plugins import get_plugin_manager


def test_plugin_hook_trigger():
    pm = get_plugin_manager()

    # Define a mock plugin
    class MockPlugin:
        @get_plugin_manager().hookimpl
        def on_pre_parse(self, raw_content: str) -> str:
            return raw_content.replace("draft", "final")

    pm.register(MockPlugin())
    res = pm.hook.on_pre_parse(raw_content="This is a draft version.")
    # Pluggy returns results in a list
    assert "This is a final version." in res


def test_local_plugin_discovery(tmp_path):
    from golem.config import GolemConfig

    # Create a dynamic plugin file in the temporary directory
    plugin_content = """
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return f"Dynamic: {raw_content}"
"""
    plugin_file = tmp_path / "my_test_plugin.py"
    plugin_file.write_text(plugin_content, encoding="utf-8")

    # Load plugin manager passing the temporary path and config
    config = GolemConfig(plugins=["my_test_plugin"])
    pm = get_plugin_manager(config=config, plugins_dir=tmp_path)

    # Verify hook can be triggered and the dynamic plugin worked
    res = pm.hook.on_pre_parse(raw_content="hello")
    assert "Dynamic: hello" in res


def test_local_plugin_error_isolation(tmp_path):
    from golem.config import GolemConfig

    # Create a broken plugin file (has runtime syntax/execution error)
    plugin_content = """
raise ValueError("Plugin failed intentionally during import!")
"""
    plugin_file = tmp_path / "broken_plugin.py"
    plugin_file.write_text(plugin_content, encoding="utf-8")

    # Loading plugins should not raise an exception, just skip broken ones
    config = GolemConfig(plugins=["broken_plugin"])
    pm = get_plugin_manager(config=config, plugins_dir=tmp_path)
    assert pm is not None


def test_plugin_hook_execution_in_build_pipeline(tmp_path):
    from golem.config import GolemConfig
    from golem.engine import BuildEngine

    # Scaffold temporary site
    content = tmp_path / "content"
    content.mkdir()
    (content / "index.adoc").write_text("This is draft content.\n", encoding="utf-8")

    # Create plugins folder and write a local hook plugin
    plugins_dir = tmp_path / "plugins"
    plugins_dir.mkdir()
    plugin_code = """
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return raw_content.replace("draft", "final")

@hookimpl
def on_post_render(html_content: str) -> str:
    return html_content.replace("Generated by Golem", "Generated by Golem and Plugin")
"""
    (plugins_dir / "test_hook.py").write_text(plugin_code, encoding="utf-8")

    # Configure Golem to load from this plugins directory and enable the plugin
    config = GolemConfig(
        content_dir=str(content),
        output_dir=str(tmp_path / "dist"),
        plugins=["test_hook"],
    )
    setattr(config, "plugins_dir", str(plugins_dir))

    engine = BuildEngine(config)
    engine.build_site()

    # Verify that the pre_parse and post_render hooks were applied to the compiled output!
    out_html = (tmp_path / "dist" / "index.html").read_text(encoding="utf-8")
    assert "final content." in out_html
    assert "Generated by Golem and Plugin" in out_html


def test_golem_add_subcommands_hookspec_execution():
    import click
    from click.testing import CliRunner
    from golem.plugins import get_plugin_manager, hookimpl

    pm = get_plugin_manager()

    class CustomCommandPlugin:
        @hookimpl
        def golem_add_subcommands(self, cli: click.Group) -> None:
            @cli.command("greet")
            @click.option("--name", default="World")
            def greet(name: str) -> None:
                click.echo(f"Hello, {name}!")

    pm.register(CustomCommandPlugin())

    @click.group()
    def test_cli():
        pass

    pm.hook.golem_add_subcommands(cli=test_cli)

    runner = CliRunner()
    result = runner.invoke(test_cli, ["greet", "--name", "Golem"])
    assert result.exit_code == 0
    assert "Hello, Golem!" in result.output


def test_config_plugins_package_loading(tmp_path, monkeypatch):
    from golem.config import GolemConfig
    from golem.plugins import get_plugin_manager

    # Create a dummy module package on sys.path
    pkg_dir = tmp_path / "custom_plugins"
    pkg_dir.mkdir()
    (pkg_dir / "__init__.py").write_text("", encoding="utf-8")
    (pkg_dir / "sample_plugin.py").write_text(
        """\
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return raw_content.upper()
""",
        encoding="utf-8",
    )
    monkeypatch.syspath_prepend(str(tmp_path))

    config = GolemConfig(plugins=["custom_plugins.sample_plugin"])
    pm = get_plugin_manager(config=config)

    res = pm.hook.on_pre_parse(raw_content="hello world")
    assert "HELLO WORLD" in res


def test_config_plugins_nonexistent_handled_gracefully():
    from golem.config import GolemConfig
    from golem.plugins import get_plugin_manager

    config = GolemConfig(plugins=["nonexistent.plugin.module.xyz"])
    pm = get_plugin_manager(config=config)
    assert pm is not None


def test_dynamic_subcommand_attached_to_click_main():
    from pathlib import Path
    from click.testing import CliRunner
    from golem.cli import main

    runner = CliRunner()
    with runner.isolated_filesystem():
        plugins_dir = Path("plugins")
        plugins_dir.mkdir()
        plugin_file = plugins_dir / "custom_cli_plugin.py"
        plugin_file.write_text(
            """\
import click
from golem.plugins import hookimpl

@hookimpl
def golem_add_subcommands(cli: click.Group) -> None:
    @cli.command("plugin-status")
    def plugin_status():
        click.echo("Plugin CLI is active!")
""",
            encoding="utf-8",
        )
        Path("golem.toml").write_text(
            """\
[plugins]
plugins = ["custom_cli_plugin"]
""",
            encoding="utf-8",
        )

        help_result = runner.invoke(main, ["--help"])
        assert help_result.exit_code == 0
        assert "plugin-status" in help_result.output

        cmd_result = runner.invoke(main, ["plugin-status"])
        assert cmd_result.exit_code == 0
        assert "Plugin CLI is active!" in cmd_result.output


def test_dynamic_subcommand_from_config_plugins(tmp_path, monkeypatch):
    from click.testing import CliRunner
    from golem.cli import main

    pkg_dir = tmp_path / "custom_cli_pkg"
    pkg_dir.mkdir()
    (pkg_dir / "__init__.py").write_text("", encoding="utf-8")
    (pkg_dir / "plugin.py").write_text(
        """\
import click
from golem.plugins import hookimpl

@hookimpl
def golem_add_subcommands(cli: click.Group) -> None:
    @cli.command("package-cmd")
    def package_cmd():
        click.echo("Executed package subcommand!")
""",
        encoding="utf-8",
    )
    monkeypatch.syspath_prepend(str(tmp_path))

    runner = CliRunner()
    with runner.isolated_filesystem():
        from pathlib import Path

        Path("golem.toml").write_text(
            """\
[site]
title = "Test Site"
author = "Test Author"

[plugins]
plugins = ["custom_cli_pkg.plugin"]
""",
            encoding="utf-8",
        )

        help_result = runner.invoke(main, ["--help"])
        assert help_result.exit_code == 0
        assert "package-cmd" in help_result.output

        cmd_result = runner.invoke(main, ["package-cmd"])
        assert cmd_result.exit_code == 0
        assert "Executed package subcommand!" in cmd_result.output


def test_unconfigured_local_plugin_is_not_registered(tmp_path):
    from golem.config import GolemConfig

    plugin_content = """\
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return f"Dynamic: {raw_content}"
"""
    plugin_file = tmp_path / "unconfigured_plugin.py"
    plugin_file.write_text(plugin_content, encoding="utf-8")

    # Without config or with empty config.plugins, the plugin should NOT be registered
    pm1 = get_plugin_manager(plugins_dir=tmp_path)
    res1 = pm1.hook.on_pre_parse(raw_content="hello")
    assert res1 == []

    config = GolemConfig(plugins=[])
    pm2 = get_plugin_manager(config=config, plugins_dir=tmp_path)
    res2 = pm2.hook.on_pre_parse(raw_content="hello")
    assert res2 == []


def test_local_plugin_lookup_keys(tmp_path):
    from golem.config import GolemConfig

    plugin_content = """\
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return f"Processed: {raw_content}"
"""
    plugin_file = tmp_path / "custom_tool.py"
    plugin_file.write_text(plugin_content, encoding="utf-8")

    # Test all 4 lookup key formats
    keys_to_test = [
        "custom_tool",
        "custom_tool.py",
        f"{tmp_path.name}.custom_tool",
        f"{tmp_path.as_posix()}/custom_tool.py",
    ]

    for key in keys_to_test:
        config = GolemConfig(plugins=[key])
        pm = get_plugin_manager(config=config, plugins_dir=tmp_path)
        res = pm.hook.on_pre_parse(raw_content="test")
        assert "Processed: test" in res, f"Failed for key: {key}"


def test_plugin_registration_order_follows_config(tmp_path):
    from golem.config import GolemConfig

    # Create two plugins that modify raw content
    (tmp_path / "plugin_a.py").write_text(
        """\
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return raw_content + " -> [A]"
""",
        encoding="utf-8",
    )

    (tmp_path / "plugin_b.py").write_text(
        """\
from golem.plugins import hookimpl

@hookimpl
def on_pre_parse(raw_content: str) -> str:
    return raw_content + " -> [B]"
""",
        encoding="utf-8",
    )

    # config.plugins in order A, then B -> Pluggy registers A then B (so B hook runs first, A second)
    config_ab = GolemConfig(plugins=["plugin_a", "plugin_b"])
    pm_ab = get_plugin_manager(config=config_ab, plugins_dir=tmp_path)
    res_ab = pm_ab.hook.on_pre_parse(raw_content="start")
    assert res_ab == ["start -> [B]", "start -> [A]"]

    # config.plugins in order B, then A -> Pluggy registers B then A (so A hook runs first, B second)
    config_ba = GolemConfig(plugins=["plugin_b", "plugin_a"])
    pm_ba = get_plugin_manager(config=config_ba, plugins_dir=tmp_path)
    res_ba = pm_ba.hook.on_pre_parse(raw_content="start")
    assert res_ba == ["start -> [A]", "start -> [B]"]


def test_get_plugin_manager_caches_entry_points(monkeypatch):
    """Verify get_plugin_manager caches entry point discovery across multiple calls."""
    import importlib.metadata
    from golem.plugins import get_plugin_manager

    # First call warms or uses the cache
    pm1 = get_plugin_manager()
    assert pm1 is not None

    # Spy on entry_points to ensure subsequent calls do not scan disk
    ep_call_count = 0
    orig_ep = importlib.metadata.entry_points

    def spy_ep(*args, **kwargs):
        nonlocal ep_call_count
        ep_call_count += 1
        return orig_ep(*args, **kwargs)

    monkeypatch.setattr(importlib.metadata, "entry_points", spy_ep)

    pm2 = get_plugin_manager()
    pm3 = get_plugin_manager()

    assert pm2 is not None
    assert pm3 is not None
    # Entry points should not have been scanned again
    assert ep_call_count == 0


def test_uniform_class_resolution_with_from_config(tmp_path, monkeypatch):
    """Verify get_plugin_manager resolves a class plugin with from_config."""
    from golem.config import GolemConfig
    from golem.plugins import get_plugin_manager

    pkg_dir = tmp_path / "custom_class_pkg"
    pkg_dir.mkdir()
    (pkg_dir / "__init__.py").write_text("", encoding="utf-8")
    (pkg_dir / "plugin.py").write_text(
        """\
from typing import Any
from golem.plugins import hookimpl, GolemPlugin

class ConfigurablePlugin(GolemPlugin):
    name = "custom_class_pkg.configurable"

    def __init__(self, greeting: str = "hello") -> None:
        super().__init__(greeting=greeting)
        self.greeting = greeting

    @classmethod
    def from_config(cls, config: Any = None) -> "ConfigurablePlugin":
        plugin_configs = getattr(config, "plugin_configs", {}) or {}
        cfg = plugin_configs.get("custom_class_pkg.configurable", {})
        return cls(**cfg)

    @hookimpl
    def on_pre_parse(self, raw_content: str) -> str:
        return f"{self.greeting}: {raw_content}"
""",
        encoding="utf-8",
    )
    monkeypatch.syspath_prepend(str(tmp_path))

    config = GolemConfig(
        plugins=["custom_class_pkg.plugin:ConfigurablePlugin"],
        plugin_configs={"custom_class_pkg.configurable": {"greeting": "howdy"}},
    )
    pm = get_plugin_manager(config=config)
    plugin = pm.get_plugin("custom_class_pkg.plugin:ConfigurablePlugin")
    assert plugin is not None
    assert plugin.greeting == "howdy"
    res = pm.hook.on_pre_parse(raw_content="world")
    assert "howdy: world" in res


def test_uniform_class_resolution_without_from_config(tmp_path, monkeypatch):
    """Verify get_plugin_manager instantiates class without from_config using cls()."""
    from golem.config import GolemConfig
    from golem.plugins import get_plugin_manager

    pkg_dir = tmp_path / "simple_class_pkg"
    pkg_dir.mkdir()
    (pkg_dir / "__init__.py").write_text("", encoding="utf-8")
    (pkg_dir / "plugin.py").write_text(
        """\
from golem.plugins import hookimpl

class SimpleClassPlugin:
    def __init__(self) -> None:
        self.initialized = True

    @hookimpl
    def on_pre_parse(self, raw_content: str) -> str:
        return f"simple: {raw_content}"
""",
        encoding="utf-8",
    )
    monkeypatch.syspath_prepend(str(tmp_path))

    config = GolemConfig(plugins=["simple_class_pkg.plugin:SimpleClassPlugin"])
    pm = get_plugin_manager(config=config)
    plugin = pm.get_plugin("simple_class_pkg.plugin:SimpleClassPlugin")
    assert plugin is not None
    assert plugin.initialized is True
    res = pm.hook.on_pre_parse(raw_content="test")
    assert "simple: test" in res


def test_uniform_class_resolution_default_config(tmp_path, monkeypatch):
    """Verify get_plugin_manager calls cls() when config is None."""
    from golem.plugins import get_plugin_manager

    pkg_dir = tmp_path / "none_cfg_pkg"
    pkg_dir.mkdir()
    (pkg_dir / "__init__.py").write_text("", encoding="utf-8")
    (pkg_dir / "plugin.py").write_text(
        """\
from typing import Any
from golem.plugins import hookimpl

class FallbackClassPlugin:
    def __init__(self, mode: str = "default") -> None:
        self.mode = mode

    @classmethod
    def from_config(cls, config: Any = None) -> "FallbackClassPlugin":
        return cls(mode="from_config")

    @hookimpl
    def on_pre_parse(self, raw_content: str) -> str:
        return f"{self.mode}: {raw_content}"
""",
        encoding="utf-8",
    )
    monkeypatch.syspath_prepend(str(tmp_path))

    # Without config, should fall back to cls() instead of from_config
    from golem.config import GolemConfig

    config = GolemConfig(plugins=["none_cfg_pkg.plugin:FallbackClassPlugin"])
    pm = get_plugin_manager(config=config)
    plugin = pm.get_plugin("none_cfg_pkg.plugin:FallbackClassPlugin")
    assert plugin is not None
    assert plugin.mode == "from_config"
